bases:
- https://github.com/bigkevmcd/taxi/deploy
configMapGenerator:
- name: stage-www-files
  files:
  - index.html
  - staging.html
images:
- name: quay.io/kmcdermo/taxi
  newTag: 815d9048ea2c054029b65d17a99b4557602c684
patchesJson6902:
- target:
    version: v1
    group: apps
    kind: Deployment
    name: taxi
  path: staging_patch.yaml
